# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MastCli < Formula
  desc "A simple TUI for sending casts"
  homepage "https://github.com/stevedylandev/mast-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.2.0/mast-cli_Darwin_x86_64.tar.gz"
      sha256 "5f94d0eb4c82773416b43fdefbbc401cc7b22e74e88dc5d2f8cfcbe246abf2a6"

      def install
        bin.install "mast"
      end
    end
    on_arm do
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.2.0/mast-cli_Darwin_arm64.tar.gz"
      sha256 "04f34ed924f382e891fd32ec4024aa177f9db4e9e8fff5d64f8e530a058913f5"

      def install
        bin.install "mast"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/mast-cli/releases/download/v0.2.0/mast-cli_Linux_x86_64.tar.gz"
        sha256 "f9d678b3a5f039cda4069d0bcde2d5220034016be58d845574a0a465d5cb0e3e"

        def install
          bin.install "mast"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/mast-cli/releases/download/v0.2.0/mast-cli_Linux_arm64.tar.gz"
        sha256 "f8074729d0737a2ac612d154c12b1367470ce847149dfc2289d680ad4eb176d1"

        def install
          bin.install "mast"
        end
      end
    end
  end
end
