# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MastCli < Formula
  desc "A simple TUI for sending casts"
  homepage "https://github.com/stevedylandev/mast-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.4.1/mast-cli_Darwin_x86_64.tar.gz"
      sha256 "5400a849c20758f3bd9c8c2f65929b0e94c54676b0523b2405dec2ba5a9f093e"

      def install
        bin.install "mast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.4.1/mast-cli_Darwin_arm64.tar.gz"
      sha256 "65874fdb4254034e993b3250e26523b5687bcb89ef7fd575ce235c1ed1023e24"

      def install
        bin.install "mast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/mast-cli/releases/download/v0.4.1/mast-cli_Linux_x86_64.tar.gz"
        sha256 "03bfc33257bc931b27bf81c53d0cfd95ca0cfea94b4910356503e676e3d9316b"

        def install
          bin.install "mast"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stevedylandev/mast-cli/releases/download/v0.4.1/mast-cli_Linux_arm64.tar.gz"
        sha256 "5fba0f06e900a99ba3bbfce04c8cb2327f7547e92e2572b60bb2c3bcc9c45610"

        def install
          bin.install "mast"
        end
      end
    end
  end
end
