# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MastCli < Formula
  desc "A simple TUI for sending casts"
  homepage "https://github.com/stevedylandev/mast-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.6.0/mast-cli_Darwin_x86_64.tar.gz"
      sha256 "8a078c2ad85f7f8ed4fa4aaee55469bb17dd5227b9f6085370ea545eb6ec81b8"

      def install
        bin.install "mast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.6.0/mast-cli_Darwin_arm64.tar.gz"
      sha256 "f04e5d6fd8d30f6454767c631dc70cca26deb557b407178c37495f06539ef969"

      def install
        bin.install "mast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.6.0/mast-cli_Linux_x86_64.tar.gz"
      sha256 "12d6c946609fb16bfbe7caec15185bc8112ad975bedede5adaea1f9a15e72861"
      def install
        bin.install "mast"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.6.0/mast-cli_Linux_armv6.tar.gz"
      sha256 "04da622975d7182e80c24f47c6b5b32e1105ddcf7549e8911ad1acdbbcb4566b"
      def install
        bin.install "mast"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/mast-cli/releases/download/v0.6.0/mast-cli_Linux_arm64.tar.gz"
      sha256 "678d1814a83255f81cf04740700ed8b73f2a77a39f12bbc63ed1d1a684fac151"
      def install
        bin.install "mast"
      end
    end
  end
end
